version: "3.2"

services:
  registry:
    tty: true
    stdin_open: true
    build:
      context: ./../registry
    links:
      - db
    environment:
      - APP_DBHOST=db
    volumes:
      - ./../registry:/opt/webapps/app
      - ./shared/ca:/opt/ca
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    restart: on-failure

  epp:
    tty: true
    stdin_open: true
    build:
      context: ./../registry
    links:
      - db
    environment:
      - APP_DBHOST=db
    volumes:
      - ./../registry:/opt/webapps/app
      - ./shared/ca:/opt/ca
    command: bash -c "rm -f tmp/pids/epp.pid && bundle exec rails server --pid tmp/pids/epp.pid -b 0.0.0.0"
    restart: on-failure

  rest_whois:
    tty: true
    stdin_open: true
    build:
      context: ./../rest_whois
    links:
      - db
    environment:
      - APP_DBHOST=db
    volumes:
      - ./../rest_whois:/opt/webapps/app
      - ./shared/ca:/opt/ca
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    restart: on-failure

  httpd:
    image: maciejszlosarczyk/httpd_epp:2.2
    tty: true
    stdin_open: true
    ports:
      # Registry
      - "80:80"
      - "443:443"
      # EPP
      - "700:700"
      # REST WHOIS
      - "800:800"
      # EPP web client
      - "900:900"
    volumes:
      - ./httpd/apache2/conf.d/logging:/etc/apache2/conf.d/logging
      - ./httpd/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./shared/ca:/opt/ca
    command: bash -c "apachectl -e info -DFOREGROUND"
    restart: on-failure

  db:
    image: postgres:9.4
    volumes:
      - ./pg:/var/lib/postgresql/data
    restart: on-failure
