version: "3"

services:
  rest-whois:
    tty: true
    stdin_open: true
    image: rest-whois
    ports:
      - "3000:3000"
    build:
      context: ../rest-whois
    links:
      - db
    environment:
      - APP_DBHOST=db
    volumes:
      - ../rest-whois:/opt/webapps/app
      - tmp:/opt/webapps/app/tmp/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    restart: on-failure
  db:
    image: postgres:9.4
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: on-failure

volumes:
  tmp:
  pg:
